/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.border.Border;

/**
 *
 * @author User
 */
public class ReportProblem extends javax.swing.JFrame {

    /**
     * Creates new form ReportProblem
     */
    final static String receiver="kilimoc@gmail.com";   
   
    
    
    public ReportProblem() {
        
        initComponents();
        setLocationRelativeTo(null);
       
       
        
        
        delete.setHorizontalAlignment(SwingConstants.RIGHT);
        attach.setHorizontalAlignment(SwingConstants.CENTER);
        //sendbtn.setBorder(null);
        Border emptyBorder = BorderFactory.createEmptyBorder();
        sendbtn.setBorderPainted(false);
        navigationPanel.setBorder(BorderFactory.createMatteBorder(2, 0, 0, 0, Color.GRAY));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sender = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        problemstatement = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        bugmodule = new javax.swing.JComboBox<>();
        navigationPanel = new javax.swing.JPanel();
        sendbtn = new javax.swing.JButton();
        attach = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Bug");

        jPanel1.setBackground(new java.awt.Color(255, 255, 242));

        jLabel1.setText("Your Email:");

        jLabel2.setText("Type the problem as it Appears");

        sender.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                senderFocusLost(evt);
            }
        });

        problemstatement.setColumns(20);
        problemstatement.setRows(5);
        jScrollPane1.setViewportView(problemstatement);

        jLabel3.setText("Select Module");

        bugmodule.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Bug Module", "Cashier", "Manager", "Director" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sender)
                            .addComponent(bugmodule, 0, 236, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bugmodule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        navigationPanel.setBackground(new java.awt.Color(255, 255, 255));
        navigationPanel.setPreferredSize(new java.awt.Dimension(519, 30));
        navigationPanel.setLayout(new java.awt.GridLayout());

        sendbtn.setBackground(new java.awt.Color(255, 255, 255));
        sendbtn.setForeground(new java.awt.Color(0, 51, 204));
        sendbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Techflay/send.png"))); // NOI18N
        sendbtn.setText("Send");
        sendbtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        sendbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendbtnActionPerformed(evt);
            }
        });
        navigationPanel.add(sendbtn);

        attach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Techflay/attachement.png"))); // NOI18N
        navigationPanel.add(attach);

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Techflay/del.png"))); // NOI18N
        navigationPanel.add(delete);

        getContentPane().add(navigationPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendbtnActionPerformed
       // JOptionPane.showMessageDialog(null, emailpassword);
        String from=sender.getText();
        String module=bugmodule.getSelectedItem().toString();
        String problem=problemstatement.getText();
        Mailer.send(from,JOptionPane.showInputDialog(null,"<html>Enter  Password for <strong>"+from+"</strong></html>"),receiver,module,problem);
    }//GEN-LAST:event_sendbtnActionPerformed

    private void senderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senderFocusLost
     
    }//GEN-LAST:event_senderFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportProblem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportProblem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportProblem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportProblem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportProblem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel attach;
    private javax.swing.JComboBox<String> bugmodule;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JTextArea problemstatement;
    private javax.swing.JButton sendbtn;
    private javax.swing.JTextField sender;
    // End of variables declaration//GEN-END:variables
}
