/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.CardLayout;
import java.sql.ResultSet;
import javafx.scene.paint.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author User
 */
public class SettleOrder extends javax.swing.JDialog {

    /**
     * Creates new form SettleOrder
     */
    String orderNo;
    CardLayout card=new CardLayout();
    private ResultSet rss=null;    
    
    
    
    CashierActivities cashac=new CashierActivities();
    public SettleOrder(JFrame frame,String orderNo) {
        super(frame,true);
        initComponents();
        this.orderNo=orderNo;        
        setLocationRelativeTo(null);
       
        paymentPanel.setBorder(BorderFactory.createMatteBorder(2, 0, 0, 0, java.awt.Color.GRAY));
        paymentPanel.setVisible(false);
        
        paymentPanel.setVisible(false);
        tcodedes.setVisible(false);
        tcodeT.setVisible(false);
        
        //load the method to populate data
        
        
        rss=cashac.getorderItems(orderNo);
        waiter.setText(cashac.getWaiter(orderNo));
        String orderv=cashac.orderSummary(orderNo).get(1).toString();
        String itemc=cashac.orderSummary(orderNo).get(0).toString();
       
        orderContent.setModel(DbUtils.resultSetToTableModel(rss));
        orderValue.setText(orderv);
        itemCount.setText(itemc);
        //get the balance
        amountDue.setText(String.valueOf(Float.parseFloat(orderValue.getText())-cashac.getPayedAmount(orderNo)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderContent = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        itemCount = new javax.swing.JTextField();
        waiter = new javax.swing.JTextField();
        orderValue = new javax.swing.JTextField();
        containerPayment = new javax.swing.JPanel();
        paymentPanel = new javax.swing.JPanel();
        amountduedes = new javax.swing.JLabel();
        amountDue = new javax.swing.JTextField();
        amountPayeddesc = new javax.swing.JLabel();
        amountPayed = new javax.swing.JTextField();
        changedes = new javax.swing.JLabel();
        change = new javax.swing.JTextField();
        transactbtn = new javax.swing.JButton();
        tcodedes = new javax.swing.JLabel();
        tcodeT = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        paymodedes = new javax.swing.JLabel();
        mode = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        disc_amount = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SETTLE ORDER FORM");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        orderContent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(orderContent);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Waiter Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Number Of Items");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Total");

        itemCount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        waiter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        waiter.setText("KILIMO K CORTNELIUS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(waiter, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(itemCount, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderValue, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderValue, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(itemCount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(waiter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        containerPayment.setLayout(new java.awt.CardLayout());

        paymentPanel.setBackground(new java.awt.Color(255, 255, 242));

        amountduedes.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 12)); // NOI18N
        amountduedes.setText("Amount Dure");

        amountDue.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 12)); // NOI18N

        amountPayeddesc.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 12)); // NOI18N
        amountPayeddesc.setText("Amount Payed");

        amountPayed.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 12)); // NOI18N

        changedes.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 12)); // NOI18N
        changedes.setText("Change");

        change.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 12)); // NOI18N

        transactbtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 12)); // NOI18N
        transactbtn.setText("Transact");
        transactbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactbtnActionPerformed(evt);
            }
        });

        tcodedes.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 12)); // NOI18N
        tcodedes.setText("Transaction Code");

        tcodeT.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 12)); // NOI18N
        tcodeT.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tcodeTMouseMoved(evt);
            }
        });

        paymodedes.setText("Select Payment Mode");

        mode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Mode", "CASH", "M~PESA", "MASTERCARD" }));
        mode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                modeItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paymodedes, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mode, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymodedes, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel4.setText("Discount Amount");

        javax.swing.GroupLayout paymentPanelLayout = new javax.swing.GroupLayout(paymentPanel);
        paymentPanel.setLayout(paymentPanelLayout);
        paymentPanelLayout.setHorizontalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paymentPanelLayout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(transactbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paymentPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(paymentPanelLayout.createSequentialGroup()
                                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tcodedes)
                                    .addComponent(amountduedes))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tcodeT, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(amountDue))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(amountPayeddesc, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(amountPayed, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(disc_amount))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(changedes, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        paymentPanelLayout.setVerticalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountduedes)
                    .addComponent(amountDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountPayeddesc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountPayed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changedes, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcodedes)
                    .addComponent(tcodeT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(disc_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(transactbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        containerPayment.add(paymentPanel, "payment");

        getContentPane().add(containerPayment, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tcodeTMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tcodeTMouseMoved
       
    }//GEN-LAST:event_tcodeTMouseMoved

    private void transactbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactbtnActionPerformed
      
       
       String amountpayable=amountDue.getText();
       String amountPayed=this.amountPayed.getText();
       String transaction_code=tcodeT.getText();
       String transaction_mode=mode.getSelectedItem().toString();      
        if(mode.getSelectedIndex() != 0){
            if(amountPayed.equals("") || Float.parseFloat(amountPayed) <= 0){
                 JOptionPane.showMessageDialog(null, "Please Amount Paid Field Should not be empty or less than 0","Techflay Software Solutions",JOptionPane.WARNING_MESSAGE);
           }
            else{
                if(mode.getSelectedIndex()!=1){
                    if(tcodeT.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "You Must Insert Transaction Code To Transact","Techflay Software Solutions",JOptionPane.WARNING_MESSAGE);
                    }
                    else{
                    cashac.savePayments(amountpayable, amountPayed, orderNo, transaction_code, transaction_mode);
                    dispose();
                    }
                    
                }
                else{
                    cashac.savePayments(amountpayable, amountPayed, orderNo, transaction_code, transaction_mode);
                    dispose();
                }
                 
               
            }
           
        }
        else{
            JOptionPane.showMessageDialog(null, "Please You must Select Transaction Mode","Techflay Software Solutions",JOptionPane.WARNING_MESSAGE);
        }
        
        cashac.recordDiscount(orderNo, waiter.getText(), Double.parseDouble(disc_amount.getText()));
        
    }//GEN-LAST:event_transactbtnActionPerformed

    private void modeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_modeItemStateChanged
        String getmode=mode.getSelectedItem().toString();
        if(getmode.equals("CASH")){
            tcodedes.setVisible(false);
            tcodeT.setVisible(false);
            
        }
        else{
            tcodedes.setVisible(true);
            tcodeT.setVisible(true);
        }
    }//GEN-LAST:event_modeItemStateChanged

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountDue;
    private javax.swing.JTextField amountPayed;
    private javax.swing.JLabel amountPayeddesc;
    private javax.swing.JLabel amountduedes;
    private javax.swing.JTextField change;
    private javax.swing.JLabel changedes;
    private javax.swing.JPanel containerPayment;
    private javax.swing.JTextField disc_amount;
    private javax.swing.JTextField itemCount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> mode;
    private javax.swing.JTable orderContent;
    private javax.swing.JTextField orderValue;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.JLabel paymodedes;
    private javax.swing.JTextField tcodeT;
    private javax.swing.JLabel tcodedes;
    private javax.swing.JButton transactbtn;
    private javax.swing.JTextField waiter;
    // End of variables declaration//GEN-END:variables
}
