/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bm.sales;

import bm.admin.DatabaseConfiguration;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author tuyeibill
 */
public class Cash extends javax.swing.JDialog {

    /**
     * Creates new form Cash
     */
    
private String orderNo;
private String amount;

 private Connection conn;
 private PreparedStatement mydata;
 DatabaseConfiguration mydb=new DatabaseConfiguration();

    
    public Cash(JFrame myjframe,String orderNo,String amount) {
        super(myjframe,true);
        initComponents();
        setLocationRelativeTo(null);
        this.orderNo = orderNo;
        this.amount=amount;
        passedOrderNo.setText(orderNo);
        amountPayable.setText(amount);
        conn=mydb.getConnection();
        debt.setVisible(false);
        debtL.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        passedOrderNo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        amountPayable = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        amountPayed = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        changep = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        debtL = new javax.swing.JLabel();
        debt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel1.setText("Order No");

        passedOrderNo.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        passedOrderNo.setText("1");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel3.setText("ORDER VALUE");

        amountPayable.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        amountPayable.setText("Ksh 500,000");

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel5.setText("AMOUNT PAYED");

        amountPayed.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        amountPayed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amountPayedKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel6.setText("CHANGE");

        changep.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jButton1.setText("Settle Order And Print Receipt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        debtL.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        debtL.setText("DEBT");

        debt.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(debtL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passedOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amountPayed, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(changep)
                            .addComponent(amountPayable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(debt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(passedOrderNo))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(amountPayable))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(amountPayed)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(changep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(debtL)
                    .addComponent(debt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountPayedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountPayedKeyReleased
        String amount=amountPayed.getText();
        float amountp=Float.parseFloat(amount);
        float change=amountp-Float.parseFloat(amountPayable.getText());
        if(change>=0){
        changep.setText(String.valueOf(change));
        }
        else{
            changep.setText(String.valueOf(0.00));
            debtL.setVisible(true);
            debt.setVisible(true);
            debt.setText(String.valueOf(change*-1));
        }
    }//GEN-LAST:event_amountPayedKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        settleOrder();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountPayable;
    private javax.swing.JTextField amountPayed;
    private javax.swing.JTextField changep;
    private javax.swing.JTextField debt;
    private javax.swing.JLabel debtL;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel passedOrderNo;
    // End of variables declaration//GEN-END:variables

    private void settleOrder() {
     //   JOptionPane.showMessageDialog(null, amountPayable.getText());
        float change=Float.parseFloat(amountPayed.getText())-Float.parseFloat(amountPayable.getText());
        int ordern=Integer.parseInt(passedOrderNo.getText());
        if(change>=0){
            
         String payorder="UPDATE  activated_orders SET status=1 WHERE orderNo='"+ordern+"'";
        try {
            mydata=conn.prepareStatement(payorder);
            mydata.execute();
            
            mydata=conn.prepareStatement("UPDATE orders SET ordervalue=amountpayed+'"+amountPayable.getText()+"',amountpayed=amountpayed+'"+amountPayable.getText()+"'WHERE orderNo='"+ordern+"'");
            boolean execute = mydata.execute();            
            JOptionPane.showMessageDialog(null, "Order Settled Suuccessful","The Grill Prime Junction Restaurant",JOptionPane.INFORMATION_MESSAGE);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Cash.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
        else{
           
            try {
                mydata=conn.prepareStatement("UPDATE orders SET ordervalue='"+amountPayable.getText()+"',amountpayed=amountpayed+'"+amountPayed.getText()+"' WHERE orderNo='"+ordern+"'");
                mydata.execute();
                JOptionPane.showMessageDialog(null, "This Order Is Partly Settled","The Grill Prime Junction Restaurant",JOptionPane.WARNING_MESSAGE);
        
            } catch (SQLException ex) {
                Logger.getLogger(Cash.class.getName()).log(Level.SEVERE, null, ex);
            }
          
                 
            
           
        }
        
    }
    
   
        
        
}
