/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bm.sales;

import bm.admin.DatabaseConfiguration;
import java.awt.BorderLayout;
import java.awt.Frame;
import java.io.InputStream;
import java.sql.Connection;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author Chris
 */
public class DailySalesReport extends javax.swing.JDialog {

    /**
     * Creates new form DailySalesReport
     */
    DatabaseConfiguration dbc=new DatabaseConfiguration();
    private Connection conn;
    public DailySalesReport(Frame myframe) {   
        super(myframe,true);
        initComponents();
        conn=dbc.getConnection();
        getDailySalesReport();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dailySalesReport = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 242));
        jPanel1.setPreferredSize(new java.awt.Dimension(702, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout dailySalesReportLayout = new javax.swing.GroupLayout(dailySalesReport);
        dailySalesReport.setLayout(dailySalesReportLayout);
        dailySalesReportLayout.setHorizontalGroup(
            dailySalesReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        dailySalesReportLayout.setVerticalGroup(
            dailySalesReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        getContentPane().add(dailySalesReport, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dailySalesReport;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

     private void getDailySalesReport(){
        try{
		InputStream stream = getClass().getResourceAsStream(("/projectReports/daily_report.jrxml"));
		JasperDesign jd = JRXmlLoader.load(stream);
  		
		JasperReport jr = JasperCompileManager.compileReport(jd);
		JasperPrint jp = JasperFillManager.fillReport(jr, null,conn);
		dailySalesReport.removeAll();
		dailySalesReport.setLayout(new BorderLayout());
		JRViewer jrviewer = new JRViewer(jp);
		dailySalesReport.add(jrviewer);
		dailySalesReport.revalidate();
		dailySalesReport.repaint(50L);
		} catch (Exception e) {e.printStackTrace();
                }
    }
}
