/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bm.sales;

//import accounts.Accounts;
import bm.admin.DatabaseConfiguration;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import accounts.Accounts;

/**
 *
 * @author "Hornbill Technologies Limited"
 */
public class MpesaPayment extends javax.swing.JDialog {

    /**
     * Creates new form MpesaPayment
     */
    DatabaseConfiguration mydb=new DatabaseConfiguration();
    private Connection conn;
    private PreparedStatement state;
    private ResultSet rs;
    
            
            
            
            
    private String orderNo;
    private String orderValue;
    public MpesaPayment(JFrame mpesaframe,String orderNo,String orderValue) {        
       super(mpesaframe,true);
        initComponents();
        setLocationRelativeTo(null);
        
        conn=mydb.getConnection();
        this.orderNo=orderNo;
        this.orderValue=orderValue;
        ordervaluepassed.setText(orderValue);
        mpesaOrderNo.setText(orderNo);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mpesaOrderNo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ordervaluepassed = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        amountReceived = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tcode = new javax.swing.JTextPane();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        change = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("M~PESA PAYMENT FORM");

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel1.setText("ORDER NO");

        mpesaOrderNo.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        mpesaOrderNo.setText("10");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel3.setText("ORDER VALUE");

        ordervaluepassed.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        ordervaluepassed.setText("Ksh.2500");

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel5.setText("AMOUNT PAID");

        amountReceived.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        amountReceived.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountReceivedActionPerformed(evt);
            }
        });
        amountReceived.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                amountReceivedFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel6.setText("Transaction Code");

        tcode.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jScrollPane1.setViewportView(tcode);

        jToggleButton1.setText("Transact");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        jLabel7.setText("CHANGE");

        change.setText("Ksh.250");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(amountReceived))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mpesaOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ordervaluepassed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(64, 64, 64)
                                .addComponent(change, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mpesaOrderNo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ordervaluepassed))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(amountReceived, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountReceivedFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amountReceivedFocusLost
        float changeV=Float.parseFloat(amountReceived.getText())-Float.parseFloat(ordervaluepassed.getText());        
        change.setText(String.valueOf(changeV));
    }//GEN-LAST:event_amountReceivedFocusLost

    private void amountReceivedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountReceivedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountReceivedActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
      float changeV=Float.parseFloat(amountReceived.getText())-Float.parseFloat(ordervaluepassed.getText());  
      new Accounts().settleOrder(Integer.parseInt(mpesaOrderNo.getText()), Float.parseFloat(amountReceived.getText()), changeV);
      //recordTransaction();
      recordTransaction();
      
      
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountReceived;
    private javax.swing.JLabel change;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel mpesaOrderNo;
    private javax.swing.JLabel ordervaluepassed;
    private javax.swing.JTextPane tcode;
    // End of variables declaration//GEN-END:variables

    private void recordTransaction() {
                    int ordern=Integer.parseInt(mpesaOrderNo.getText());

        try {       
            
            state=conn.prepareStatement("INSERT INTO mpesa_sales(orderNo,amount,transaction_code) VALUES(?,?,?)");
            state.setInt(1,Integer.parseInt(mpesaOrderNo.getText()));
            state.setBigDecimal(2, BigDecimal.valueOf(Float.parseFloat(amountReceived.getText())));
            state.setString(3, tcode.getText());
            state.execute();
            JOptionPane.showMessageDialog(null, "Order Settled Successfully", "The Grill Prime Junction Restaurant", JOptionPane.INFORMATION_MESSAGE);
            //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methos, choose Tools | Templates.
        } catch (SQLException ex) {
            Logger.getLogger(MpesaPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
